feat: added default headers to error headers
Homeservenow/serverless-aws-handler pull request #25
Opened 2020-10-02 12:20 UTC by bashleigh

Added default headers to error responses

2020-10-02 13:38 UTC, AlexHayton requested changes
Looking pretty solid, but I think we need to add a test case to demonstrate that we're dealing with "an unhandled exception that has default headers defined" correctly.

Also a minor tidy up suggestion...

2020-10-02 13:38 UTC, AlexHayton commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
Couldn't we just do `isHttpErrorException(error) ? error.headers : {}` now?

2020-10-02 13:41 UTC, bashleigh commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
then you don't get your defaults?

2020-10-02 13:55 UTC, AlexHayton commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
I mean the entire block would look like this:
```
headers: {
    ...defaultHeaders,
    ...isHttpErrorException(error) ? error.headers : {}
},
```

2020-10-02 13:55 UTC, AlexHayton commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
In the above case the two get merged, so all those lovely CORS headers should still be there.

2020-10-02 15:34 UTC, bashleigh commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
I think originally I wanted to return undefined so headers didn't exist if there were none but tbh, we could return them anyway. Especially now I'm returning an empty object so headers are always set as empty array regardless

2020-10-03 18:58 UTC, bashleigh commented on src/http/http.error.handler.ts
> +    ...(isHttpErrorException(error) && Object.keys(error.headers).length >= 1
added test

2020-10-06 15:27 UTC, merged